require 'plugins.color-scheme'

require 'plugins.plenary'

require 'plugins.conform'
require 'plugins.treesitter'
require 'plugins.fzf'
require 'plugins.fff'
require 'plugins.lint'
require 'plugins.blink'
require 'plugins.indent'

require 'plugins.mini-diff'
require 'plugins.mini-files'
require 'plugins.mini-icons'
require 'plugins.mini-ai'
require 'plugins.mini-pairs'
require 'plugins.mini-statusline'
require 'plugins.mini-surround'
require 'plugins.mini-clue'

-- require 'plugins.cd-project'
require 'plugins.comfy-line-numbers'
require 'plugins.guess-indent'
require 'plugins.vim-tmux-navigator'
require 'plugins.render-markdown'
require 'plugins.mdx'
require 'plugins.logs'
require 'plugins.rip'
require 'plugins.fold-imports'
require 'plugins.refactor'
require 'plugins.99'
-- require 'plugins.pi'
